// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI/migrations can use a direct (or session-pooler) connection while
    // application traffic uses the transaction pooler on Vercel.
    url: process.env["DIRECT_URL"] || process.env["DATABASE_URL"],
  },
});
